# Netlify Configuration for Elevate Admin Frontend

[build]
  # Build command
  command = "npm run build"
  # Output directory
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# No timeout for API calls - they go directly to backend
# Large file uploads bypass Netlify entirely

